### PR TITLE
Support KOR region

### PR DESCRIPTION
**Pull request by d3m3vilurr**
Sorry, only checked ropbin mode with browserhax on n3ds 10.1.0-23K (menu version 8192)

### CODE REVIEW

**Comment by smealum** [comment]
i take it this has been tested ?

**Comment by d3m3vilurr** [comment]
Only ropbins tested v8192 to v11266  (home menu version 10.0 to 10.5) using browserhax.
Browserhax rops already merged :)
All builded ropbin binaries uploaded to http://bhx.suod.kr/payloads/ropbin/N3DS_{VERSION}K_ROP.bin (eg: http://bhx.suod.kr/payloads/ropbin/N3DS_10.3K_ROP.bin),
so some korean users [help to working test](http://www.fafan.kr/board/view.aspx?id=ndsbbs&rno=11488&page=1).

BTW, I was tried to port oot3dhax Korea version, but my porting code just crash and still not work(I think, it is just my mistake..) so, I cannot test otherapps bin yet.

**Comment by d3m3vilurr** [comment]
otherapp payload tested (but just tested emunand 10.1K)

**Comment by smealum** [comment]
thanks for your contribution. will do my best to update web stuff this week.

**Comment by rodri042** [comment]
I'm trying to find the otherapp-o3ds-10.7 - 28 payload for **KOR**. Is already on the websites?

Where I can find it?
Thanks!

**Comment by smealum** [comment]
it's not on there yet, i'm hoping to add it this weekend.

**Comment by yellows8** [comment]
@d3m3vilurr You didn't update buildAll.py, please fix that with another PR.

**Comment by d3m3vilurr** [comment]
@yellows8 maybe fixed #10

**Comment by d3m3vilurr** [comment]
@yellows8 append patch 296cf85 to #10 
I only checked enableotherapp mode

**Comment by yellows8** [comment]
:)

**Pull request merged**
