### PR TITLE
Cleanup MENU version maps

### PR DESCRIPTION
**Pull request by d3m3vilurr**
- buildVersion.py: manually conditions to dict base switch
- Makefile: use local `ctrulib` instead of devkitpro ihaveamac/ninjhax2.x@222d5090d79

### CODE REVIEW

**Comment by smealum** [comment]
thx, only thing is this repo is meant to work with python3 so i'm going to change itermitems to items, but other than that this is nice

**Comment by yellows8** [comment]
@d3m3vilurr Did you ever test KOR title-takeover with mset?

**Comment by d3m3vilurr** [comment]
@yellows8 I was only tested can launch hbl and some homebrew apps on browserhax and basehaxx. also not tested on the 9.6; only tested n3ds 10.1 and o3ds 10.3
btw, i don't remember well.. n3ds can launch titles with HANS, but o3ds can't. need you this result?

**Comment by yellows8** [comment]
"n3ds can launch titles with HANS, but o3ds can't. " Huh?

**Comment by d3m3vilurr** [comment]
they depend just my memory. i remember n3ds can launch well, but o3ds can't remember clearly....
need you retest this?

**Comment by yellows8** [comment]
Sure.

**Comment by d3m3vilurr** [comment]
ok. i will test asap :)

**Comment by d3m3vilurr** [comment]
HANS launch system menu well on the O3DS 10.3K with basehaxx.
I remember problem of HANS on O3DS, cannot return to hbl with L+R+DOWN+B.
I was reinstall payload of last version before test, currently look good.

what mean `test KOR title-takeover with mset`?

**Comment by yellows8** [comment]
"system menu" Huh?

**Pull request merged**
